include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - 'firebase_options.dart'
  errors:
    invalid_annotation_target: ignore # Freezed

linter:
  rules:
    type_annotate_public_apis: false