name: flutter_scaffold #TODO: Update project name
description: Flutter Scaffolding Project #TODO: Update project description
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.2.0
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  collection: ^1.15.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.3
  freezed_annotation: ^1.1.0
  geolocator: ^8.2.1
  get_it: ^7.2.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  keyboard_dismisser: ^2.0.1
  package_info_plus: ^1.3.0
  permission_handler: ^8.3.0
  reactive_forms: ^13.0.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.3

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.11
  clock: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.0
  lint: ^1.8.2
  mockito: ^5.0.10
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/

#TODO: Update app icons
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"
