name: flutter_scaffold #TODO: Update project name
description: Flutter Scaffolding Project #TODO: Update project description
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.2.0
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  collection: ^1.15.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.3
  flutter_native_splash: ^2.2.4
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  keyboard_dismisser: ^3.0.0
  loader_overlay: ^2.0.7
  package_info_plus: ^1.3.0
  permission_handler: ^10.0.0
  reactive_forms: ^13.0.0
  retrofit: '>=3.0.0 <4.0.0'
  share_plus: ^4.0.10
  slang: ^2.6.0
  slang_flutter: ^2.6.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.3

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.11
  clock: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  json_serializable: ^6.1.0
  lint: ^1.10.0
  mockito: ^5.0.10
  mocktail: ^0.3.0
  retrofit_generator: '>=4.0.0 <5.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

#TODO: Update app icons files
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"
